### ISSUE TITLE
Running a task with long output breaks nvim

### ISSUE THREAD

**Issue by dCubelic** [Shatur/neovim-tasks#10]
If i create a task that finishes quickly, but has a long output (e.g. `cat`-ing a long file), the whole nvim slows down, stops reacting to my inputs, and nothing happens even if I do `Task cancel`. The only option is to wait until the output finishes, or closing nvim and opening it again.

The file I'm testing it with is a text file of ~150MB

example of the task:
```lua
local cat = {}

cat.tasks = {
    cat = function()
        return {
            cmd = 'cat',
            args = { '/Users/username/Downloads/rockyou.txt' },
        }
    end
}

return cat
```

Expected behaviour would be for the task to stop printing output if I do `Task cancel`, so I can continue with my usual workflow.

**Comment by Shatur** [comment]
You can cancel regular tasks, but if a task prints a lot of output - there is nothing I can do about it. The issue is in quickfix that response slowly and freeze Neovim on a lot of output.

**Comment by DoDoENT** [comment]
Would that also be an issue if the plugin used a terminal for running the tasks and then just copied all the results back into the quick-fix list?
Then, if cancellation happens, only the so-far printed output would be copied to the quick-fix list, which would probably be more manageable. Any thoughts on that?

**Comment by Shatur** [comment]
That's basically what the plugin is doing already. It runs a task in background using `Plenary.Task` and prints output to quickfix.
But we currently do it every time when a new buffered output is available. Probably it would be faster if we do it once only at the end. So I would try to add a parameter to a task whether to show output in quickfix at the end.

**Comment by dCubelic** [comment]
That could fix the problem, but then I would not have a 'live' update of the qflist, right?

I do not know I wish to cancel my task before I can see some "faulty" output.

**Comment by Shatur** [comment]
> That could fix the problem, but then I would not have a 'live' update of the qflist, right?

Yes

> I do not know I wish to cancel my task before I can see some "faulty" output.

Sorry, but I currently don't see a solution for it.

**Comment by dCubelic** [comment]
I opened an [issue](https://github.com/nvim-lua/plenary.nvim/issues/468) in plenary. Maybe they will have a solution
