### ISSUE TITLE
Task cancel does not cancel

### ISSUE THREAD

**Issue by DoDoENT** [Shatur/neovim-tasks#13]
I'm running `ctest` with parallel tests via `neovim-task`.

By issuing `:Task cancel`, it first kills the underlying ctest, but processes spawned by `ctest` keep running (I can see them in Activity Monitor).

By issuing the second `:Task cancel`, I get the message "No running process".

However, when I run the `ctest` from the terminal and hit ctrl+c, both `ctest` and all spawned processes get terminated.

**Comment by Shatur** [comment]
What OS are you using? Because on Linux all child precessed will be killed automatically.
But on Windows we doing it manually:
https://github.com/Shatur/neovim-tasks/blob/6e37ddc4702f100d18a4b4869ff89d275284b95b/lua/tasks/runner.lua#L216-L225

**Comment by DoDoENT** [comment]
MacOS 13.4.1

**Comment by DoDoENT** [comment]
Here you are: https://github.com/Shatur/neovim-tasks/pull/14

**Comment by DoDoENT** [comment]
Thank you for the quick merge.
