### ISSUE TITLE
"auto" task not working when cargo not installed

### ISSUE THREAD

**Issue by undyamon** [Shatur/neovim-tasks#17]
There seems to be an issue with the `cargo.lua` module.

Basically, loading the module requires `cargo` being installed:
- the definition of `cargo.tasks` [calls](https://github.com/Shatur/neovim-tasks/blob/f42b164499b6e833ac6b94993abc215fc4a0db17/lua/tasks/module/cargo.lua#L170) `get_cargo_subcommands()`;
- it, in turn, [creates a new `Job`](https://github.com/Shatur/neovim-tasks/blob/f42b164499b6e833ac6b94993abc215fc4a0db17/lua/tasks/module/cargo.lua#L83-L86) running `cargo`;
- `Job:new(...)` from plenary.nvim [checks](https://github.com/nvim-lua/plenary.nvim/blob/366b0837486f60ae0e7550c15de8ff66d057c4cd/lua/plenary/job.lua#L105-L108) whether the command is executable and fails if it's not.

This is a problem when using `auto` as the target module, since this will [try to load every module](https://github.com/Shatur/neovim-tasks/blob/f42b164499b6e833ac6b94993abc215fc4a0db17/lua/tasks/utils.lua#L81-L86) to call the appropriate `condition()`, even when `cargo` is not installed.

Personally, I would check this in `get_cargo_subcommands` as

```lua
local cmd = 'cargo'
local ok, is_exe = pcall(vim.fn.executable, cmd)
if ok and 1 ~= is_exe then
  utils.notify('Unable to find "cargo" executable', vim.log.levels.WARN)
  return {}
end

local job = Job:new({
  command = cmd,
  args = { '--list' },
  enabled_recording = true,
})
job:sync()

if job.code ~= 0 or job.signal ~= 0 then
  utils.notify('Unable to get list of available cargo subcommands', vim.log.levels.WARN)
  return {}
end
```

Hope this helps!

**Comment by Shatur** [comment]
Makes sense to me. Could you open a PR?
